apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-service
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
spec:
  rules:
  - host: shub.test
    http:
      paths:
      - path: /
        backend:
          serviceName: example-service
          servicePort: 80
